### ISSUE TITLE
Using a small, cropped face image as texture after fitting leads to an image access outside domain error

### ISSUE THREAD

**Issue by AdamKortylewski** [unibas-gravis/scalismo-faces#106]
BUG:

The code crashes when fitting face images where the face is partially outside of the image.

Please change line 45 in `TextureExtraction.scala`

`Some(target(imagePoint.x + 0.5, imagePoint.y + 0.5))`

to

`Try(target(imagePoint.x + 0.5, imagePoint.y + 0.5)).toOption`

Thank you

**Comment by Andreas-Forster** [comment]
Thanks for reporting this error. I think this is a good solution as invisible points are represented as None when accessing them anyway.

see in [imageAsSurfaceProperty](https://github.com/unibas-gravis/scalismo-faces/blob/e49a6922d9430bc3a09031e35ea4bbeb42d651f4/src/main/scala/scalismo/faces/render/TextureExtraction.scala#L41-L48)

**Comment by andreas-schneider** [comment]
As an easy fix you can set the AccessMode of the image with 
```scala
val outsideValue = ???
image.withAccessMode(AccessMode.Padded(outsideValue))
```
this way the texture will be filled outside the image with `outsideValue`.

**Comment by Andreas-Forster** [comment]
This will still be possible if we add the `Try`-`toOption` fix. But this fix will prevent future crashing and in my opinion it makes sense.
