### ISSUE TITLE
Add simple fitting script: tutorial style

### ISSUE THREAD

**Issue by sschoenborn** [unibas-gravis/scalismo-faces#20]
Add a simple but working fitting script to illustrate fitting with the MCMC framework

**Comment by BernhardEgger** [comment]
The Tutorial is now available under http://gravis.dmi.unibas.ch/PMM/ and a fitscript following the publication:

Markov Chain Monte Carlo for Automated Face Image Analysis
Sandro Schönborn, Bernhard Egger, Andreas Morel-Forster and Thomas Vetter
International Journal of Computer Vision 123(2), 160-183 , June 2017
DOI: http://dx.doi.org/10.1007/s11263-016-0967-5

is available here:
https://github.com/unibas-gravis/basel-face-pipeline/blob/master/src/main/scala/fitting/StandardFitScript.scala
