### ISSUE TITLE
Gamma correction is only partially implemented

### ISSUE THREAD

**Issue by sschoenborn** [unibas-gravis/scalismo-faces#25]
Gamma correction between sRGB and RGB exists only partially. Do not use v0.4.0 for working with meshes or models yet!

- PixelImage is nicely handled and read as sRGB, work is in linear space - ok
- Meshes are read as RGB and thus wrong - values are actually sRGB in mesh files
- Models are read as RGB and thus wrong - values are actually sRGB in model files

--> wrong renderings with images which are too bright (double gamma correction)

Suggested "fix" for now: 

Stick with sRGB values only and ignore gamma correction for a moment - Everything in framework is referring to sRGB then (but just called RGB internally). This is what is most convenient, expected and consistent and it has been before. But for physical rendering and illumination/shadow correction, this is not really correct. But we have to live with that for the moment to keep everything consistent. Gamma correction should still be available for those who know how to use it explicitly.

**Comment by andreas-schneider** [comment]
This is solved by PR #28 .

**Comment by sschoenborn** [comment]
closed with #28
